# Site settings
# Site settings
title: My Jekyll
email: maplecumtcs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  One step.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.maplecumt.com" # the base hostname & protocol for your site
twitter_username: maplecumt
github_username:  maplecumt

# Build settings
markdown: kramdown

#duoshuo
duoshuo_id: maplecumt
duoshuo_short_name: maplecumt